version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(actions)'

  # Maintain dependencies for npm
  - package-ecosystem: 'npm'
    directory: '/orgs'
    schedule:
      interval: 'daily'
    allow:
      - dependency-type: 'production'
      - dependency-type: 'development'
    commit-message:
      prefix: 'feat(deps)'
    groups:
      docusaurus:
        patterns:
          - '@docusaurus*'

  - package-ecosystem: 'npm'
    directory: '/organized'
    schedule:
      interval: 'daily'
    allow:
      - dependency-type: 'production'
      - dependency-type: 'development'
    commit-message:
      prefix: 'feat(deps)'
    groups:
      docusaurus:
        patterns:
          - '@docusaurus*'
